### ISSUE TITLE
Repurpose create form as "edit" form for job definitions

### ISSUE THREAD

**Issue by jweill-aws** [jupyter-server/jupyter-scheduler#172]
### Problem

Users want to be able to edit a job definition (JD) and either save it in place, or create a new job definition (aka "cloning" a job definition). See #87.

### Proposed Solution

Add a button called "Edit Job Definition" (to be confirmed) on the Job Definition Detail page. When the user clicks this button, they are brought to the Create Job form with the job definition detail prepopulated.

The Create Job form:
1. May benefit from having a different title ("Edit _[job definition name]_", for example)
2. Should have buttons "Cancel," "Save Changes," and "Save as New Job Definition"
  a. **Cancel** returns the user to the Job Definition Detail page from which they came (it should _not_ send the user to the JD list page, as it does today)
  b. **Save Changes** should, if all inputs are valid and if the API request succeeds, return users to the JD detail page from which they came.
  c. **Save as New Job Definition** should, if all inputs are valid and if the API request succeeds, take users to the JD list page, as the "Create JD" form does today.
4. Might _not_ let users switch to "Run now" — to be discussed

### Additional context

If the schedule of the job definition was created using an "easy scheduling" option, we should prepopulate the create form so that easy scheduling appears by default, with options preselected. (This may require you to interpret the cron schedule.)

**Comment by dlqqq** [comment]
Per team discussion on 11/1/2022:

- Save as New Job Definition is not currently possible due to us not persisting input URI in the record anymore.
- Populating easy scheduling is technically challenging and brittle without some persistence of a "scheduling format" in the backend. Because users can still use easy scheduling while changing the schedule, this isn't that much of a value-add.

Thus we are limiting the scope and excluding the above 2 features from this issue. Feel free to open another issue if these features are requested again.
