### ISSUE TITLE
Validate parameter handling

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-server/jupyter-scheduler#229]
## Description

I believe we need to do some additional work to validate how parameters are being handled. We should test different parameter types and kernels (R, Python, etc.)

**Comment by dlqqq** [comment]
cc @3coins @ellisonbg 

The current behavior, funny enough, only correctly handles integer parameter values. `ParameterValues` is defined as a union:

```
ParameterValues = Union[int, str, float, bool]
EnvironmentParameterValues = Union[int, str, float, bool]
```

However, pydantic always attempts to cast to the first union member. [From the documentation](https://pydantic-docs.helpmanual.io/usage/types/#unions):

> pydantic will attempt to 'match' any of the types defined under Union and will use the first one that matches. In the above example the id of user_03 was defined as a uuid.UUID class (which is defined under the attribute's Union annotation) but as the uuid.UUID can be marshalled into an int it chose to match against the int type and disregarded the other types.

Therefore, if coercion to int fails, it tries to coerce to str, which almost always succeeds. Thus we have two options:

1. If we want to restrict the type of parameter values while supporting the other primitives listed in that union, we simply have to move `str` to the end of the list of union members.
2. If we want to allow any expression (interpretable by the kernel), we will have to delete these types and always interpret a parameter value as a `str`. Then we will have to always do `content.append(f"{key} = {value}")` and never auto-wrap in double quotes in `parameterize.py`.
  - This is technically a regression since we will no longer automatically wrap parameter values intended as strings in double quotes; users will have to specify them manually.

I'm in favor of approach 2) as it allows us to virtually support any kernel, and is the easiest to implement. I believe this also preserves parity with papermill.

**Comment by 3coins** [comment]
@dlqqq Thanks for that assessment. I am assuming that with 2, users will be able to specify strings with only single quotes, double quotes will not work. Is that correct? Also, the model type will be "str" in this case, allowing any value to be interpreted as string.

**Comment by dlqqq** [comment]
@3coins Double quotes should work because the backend is literally receiving double quotes as part of the request, meaning they're "already escaped" in a sense. I'll make sure to test this though.

> the model type will be "str" in this case, allowing any value to be interpreted as string.

Yup.
