### ISSUE TITLE
Job name validation

### ISSUE THREAD

**Issue by jweill-aws** [jupyter-server/jupyter-scheduler#234]
### Problem

The job name is not validated; any value, including no value, is accepted for all environments. Sometimes, an environment does not accept certain characters in a job name, causing job runs to fail.

### Proposed Solution

Allow environments to provide validation rules, such as a regular expression (regex) for job names or a list of acceptable characters in job names. Block form submission if a name fails environment validation. Validate the job name upon environment selection or change.

Note that some regex grammars are Turing-complete, introducing a security vulnerability.

**Comment by jweill-aws** [comment]
Consider a general regex permitting alphanumerics, periods, hyphens, and underscores, with a maximum total length of 63:`^[a-zA-Z0-9.][a-zA-Z0-9.-_]{0,62}$`

Because we use the filename as the default job name, we will have to sanitize the filename upon job creation.

**Comment by dlqqq** [comment]
@jweill-aws While this is OK for now, we should look into using a validator library (e.g. yup, zod) that allows us to return specific error messages on a case-by-case basis. For example, it should return "name is too long" when it validation failing because the name is too long. Right now, the regex approach can't do much better than saying "something is wrong" rather than telling them exactly what is wrong.

**Comment by ellisonbg** [comment]
Also, I just noticed that we allow the job name to be empty. If you provide an empty job name, the link to the job detail view is broken in the list view (there is no name to attach the link to). Should we require a job name?

**Comment by jweill-aws** [comment]
In the past, we fell back to displaying a placeholder like ''(no name)'' when users haven't provided a name. We could reinstate that.

**Comment by jweill-aws** [comment]
Per discussion, blank names will no longer be accepted as a result of this issue's being fixed.
