### ISSUE TITLE
Provide the ability to disable creation besides errors

### ISSUE THREAD

**Issue by awaisabir** [jupyter-server/jupyter-scheduler#282]
### Problem
Right now I believe the ability to disable the create button is only exposed through errors via the `handleErrorsChange` prop. If consumers want to block the creation of a job based on an asynchronous action related to Additional Options, the only way they can achieve that is by manipulating errors in some way (which is not ideal). The feature I am proposing is for a prop to be exposed, that allows consumers to directly take control of the `disabled` state of the `Create` button.

### Proposed Solution
Introduce a new piece of state that keeps track of the disabled state for the Create job button

An example implementation [for Create Job](https://github.com/jupyter-server/jupyter-scheduler/blob/main/src/mainviews/create-job.tsx) could look something like this:
```ts
// initial value is false
const [disableCreation, setDisableCreation] = useState(false);

/**
 * in a useEffect you can instead check for changes in errors
 * and update the disabled state if there are any changes in errors detected
 **/
useEffect(() => {
  const anyAdvancedErrors = Object.keys(advancedOptionsErrors).some(
    key => !!advancedOptionsErrors[key]
  );

  const anyErrors = Object.keys(errors).some(key => !!errors[key]) || anyAdvancedErrors;

  setDisableCreation(anyErrors);
}, [advancedOptionErrors, errors]);

/**
 * pass the setDisableCreation down to the advanced options as well
 **/
<props.advancedOptions
  jobsView={JobsView.CreateForm}
  model={props.model}
  handleModelChange={props.handleModelChange}
  errors={advancedOptionsErrors}
  handleErrorsChange={setAdvancedOptionsErrors}
  updateDisabledState={setDisableCreation} // new prop
/>
```

As a consumer, I can now manipulate errors and disable the button AND also have the ability to directly block the create button if my asynchronous action - an API request, etc; is taking longer than expected

This is not absolutely necessary, but is definitely an enhancement. Let me know what the team thinks 😄

**Comment by dlqqq** [comment]
For your use case, it'd be easier to just set an error key to be true while the API request is in flight, and then set it to be false upon response. If you want to abstract this away, you can write a custom callback to toggle a specific key in the errors object.

We want to avoid duplicate state. It doesn’t make sense for disabled to be separate from the errors object, since disabled should always be set to true whenever any value in the errors object is truthy. While you could keep them in sync easily via an effect hook, it’s easier to just to not make disabled a separate state variable.
