### ISSUE TITLE
Editing parameters causes cursor to jump to end of input

### ISSUE THREAD

**Issue by jweill-aws** [jupyter-server/jupyter-scheduler#34]
## Description

While editing the name or value of a parameter, the cursor jumps to the end of the input box after every character entry. This is present in the code in #32.

https://user-images.githubusercontent.com/93281816/191857029-51e5d3c2-a5ff-4394-9504-49dc62870dbf.mov

## Reproduce

Click in the middle of the name or value of a parameter. Type a character. The character is inserted at that position and the cursor moves to the end of the input.

## Expected behavior

The cursor appears immediately following the inserted character.

## Context

This does not occur with other text inputs in this form.

This appears to be common behavior with React when the state update is not fast enough. I attempted to remediate this using local state, as mentioned below, but I didn't have the same success with the parameter inputs as I did with the standalone inputs.

* https://github.com/facebook/react/issues/955
* https://stackoverflow.com/questions/28922275/in-reactjs-why-does-setstate-behave-differently-when-called-synchronously/28922465#28922465

**Comment by dlqqq** [comment]
Yup. The root of the issue is that the VDOM update is being fired asynchronously by Lumino. Looks like this crazy call flow is what’s happening.

1. invoke `Widget.model.stateChanged.emit` (where `stateChanged` is a Lumino signal)
2. call `Widget.update()`
3. call `MessageLoop.postMessage(…)`
4. call `MessageLoop.enqueueMessage(…)` , appends to end of message queue, and then
5. call `MessageLoop.schedule(...)`
6. (ASYNC STEP) call `requestAnimationFrame(…)`
7. call `MessageLoop.runMessageLoop(…) `
8. call `Widget.processMessage(…)`
9. call `Widget.notifyLayout(...)` and `ReactWidget.onUpdateRequest(...)`
10. which finally just calls `ReactWidget.updateDOM(…)`

Getting the model to just directly call ReactWidget.updateDOM(…) synchronously before step 1) would mean that the VDOM value is updated synchronously after `input.value` is updated, which would fix this issue.
