### ISSUE TITLE
Output formats are not passed properly from Job Details view to Create Job form

### ISSUE THREAD

**Issue by jweill-aws** [jupyter-server/jupyter-scheduler#54]
## Description

In `rerunJob` in `job-detail.tsx`, the output formats are passed as `name: format, label: format` where `format` is `'ipynb'` or `'HTML'`:

https://github.com/jupyter-server/jupyter-scheduler/blob/c776e2dfc07c0c863c78473ceefd3836dd54d81b/src/mainviews/job-detail.tsx#L64-L78

Because these output formats do not match those in the environment's output formats list, they will never be selected on the create job form.

## Expected behavior

The jobs should be in the same format as is used in the environments list's environment definition: for example, `{ name: 'ipynb', label: 'Notebook' }`.

## Context

The utility function `outputFormatsForEnvironment` is used to get an environment's properly formed output formats.

**Comment by ellisonbg** [comment]
@andrii-i @jweill-aws is this still valid?

**Comment by andrii-i** [comment]
Implementation changed but the issue is still valid. But now it's about it is now about adding missing outputFormats conversion functionality in `convertDescribeJobtoJobDetail` function of `model.ts` (line 130)

https://github.com/jupyter-server/jupyter-scheduler/blob/5fd1856910bc2d90bb5c1c24cdfd06c6e351e160/src/model.ts#L108-L140
